# Generated by Django 4.2.16 on 2024-10-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(blank=True, max_length=30, null=True)),
                ('deparment', models.CharField(blank=True, max_length=30, null=True)),
                ('regno', models.IntegerField(blank=True, null=True)),
                ('phoneno', models.BigIntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('mark', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
