# Generated by Django 5.1.4 on 2024-12-18 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_studenttable_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultytable',
            name='sid',
        ),
        migrations.AddField(
            model_name='facultytable',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='administrator.logintable'),
            preserve_default=False,
        ),
    ]
