# Generated by Django 5.1.4 on 2024-12-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_remove_facultytable_sid_facultytable_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='deparment',
            new_name='department',
        ),
    ]
